### ISSUE TITLE
匹配网站太暴力了

### ISSUE THREAD

**Issue by mougua** [rose1988c/Caoliu.plug#7]
自己做点小网站，今天调试一个网页的样式怎么样都不对，而且只是“文章(article)”页面有问题，但本机程序里面怎样查都查不到相关的样式代码。最后发现，原来article这个url（包含cl）触发了草榴脚本里的style。。。_(:з」∠)_

**Comment by rose1988c** [comment]
# # ，非常抱歉~~~ 已修复
